apiVersion: locationtracker/v1
kind: Deployment
metadata:
  name: kube-deployment
  labels:
    app: kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
        - name: kube
          image: kubepractice:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always